version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/readme/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/licenses/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/gitignore/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/rat/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/gitattributes/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/gitmodules/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/notices/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/gitrepo/"
    schedule:
      interval: "daily"
