version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/readme/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/licenses/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/gitignore/"
    schedule:
      interval: "daily"
